---
title: "AI Technology Final Project"
author: "John Morse"
format:
  docx: default
  html: default
  pdf:
    documentclass: scrartcl
    classoption: landscape
editor: visual
---

## Notes on Requirements

Description: Written Report (3-5 pages, single spaced) explaining your tool’s purpose, implementation, limitations, and relevance to public policy

**Deliverable #3:**

-   Introduction: Describe the modal use case, intended audience, and public policy relevance

    -   **Policy Relevance & Use Case (15 pts):** Prototype is situated in a real public policy, government, or civic context.

-   Technical Summary: Outline the tools, model(s), corpus, and workflows you decided to use

    -   **Technical Implementation & Documentation (20 pts):** Clear explanation of tools, models, and workflows (e.g., HuggingFace, R/reticulate).

-   Governance and Risk: Discuss transparency, bias, hallucination, or other concerns that are relevant to your tool

    -   **Governance, Ethics, and Risk Discussion (15 pts):** Addresses transparency, bias, hallucinations, fairness, and governance issues.

-   User Considerations: Reflect on usability, limitations, and what “success” looks like

-   Next Steps: Suggest future directions or improvements, and how this work could inform a potentially real-world deployment

    -   **Future Implications & Next Steps (10 pts):** Addresses potential improvements, implications for deployment, and governance impacts.

## Introduction

&&&

## Technical Summary

This solution was written in R version 4.4.1 and developed inside the RStudio environment provided by Posit (<https://posit.co>). Additionally, the R `reticulate` library was used to import Python based libraries supporting the Hugging Face (<https://huggingface.co>) LLM models. Python was installed through Anaconda, and Python version 3.10.19 was used to access LLM models.

### R Libraries

-   `tidyverse` - provides a range of data science and data analysis tools for R.

-   `reticulate` - allows access to Python libraries within R.

-   `glue` - used to concatenate strings including inserting variables.

### Python Libraries

The following libraries were imported into the R environment through `reticulate`.

`sentence_transformers` -

`transformers` -

### Models

-   MiniLM - `sentence-transformers/all-MiniLM-L6-v2` - provides tokenization and embeddings for RAG corpus and query. Allows comparison of user query to RAG corpus based on cosine-similarity.

Mistral-7B-Instruct - mistralai/Mistral-7B-Instruct-v0.1 - &&&

### Workflow

&&&

## Governance and Risk

Hallucination is a consideration with the LLM used. As an example, in one query, the model referred to an executive order within the corpus provided but wrongfully attributed it to former President Biden. This is likely due to a confusion with the pre-trained corpus identifying executive orders previously signed by Biden.

## User Considerations

&&&

## Next Steps

&&&
